apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ubuntu
    spec:
      containers:
        - name: ubuntu-tz
          command: ["/bin/bash","-c","--"]
          args: ["while true; do sleep 30; done;"]
          securityContext:
            privileged: true
          image: ubuntu:16.04
